services:
  mongo-container:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - ./data:/data/db
    ports:
      - "27017:27017"
    command: mongod
    restart: unless-stopped